export type EmojiEntry = { emoji: string; name: string; aliases: string[]; category: string };

export const EMOJIS: EmojiEntry[] = [
  {emoji:'😀',name:'grinning face',aliases:['grin','happy','smile'],category:'Smileys'},
  {emoji:'😃',name:'smiling face with big eyes',aliases:['happy','smile','joy'],category:'Smileys'},
  {emoji:'😄',name:'smiling face with smiling eyes',aliases:['happy','smile','joy'],category:'Smileys'},
  {emoji:'😁',name:'beaming face',aliases:['grin','teeth','happy'],category:'Smileys'},
  {emoji:'😆',name:'grinning squinting face',aliases:['laugh','lol','haha','funny'],category:'Smileys'},
  {emoji:'😅',name:'grinning face with sweat',aliases:['nervous','relief','sweat','lol'],category:'Smileys'},
  {emoji:'😂',name:'face with tears of joy',aliases:['laugh','lol','crying laugh','haha','funny'],category:'Smileys'},
  {emoji:'🤣',name:'rolling on the floor laughing',aliases:['rofl','laugh','lol','haha'],category:'Smileys'},
  {emoji:'🙂',name:'slightly smiling face',aliases:['smile','fine','okay'],category:'Smileys'},
  {emoji:'🙃',name:'upside down face',aliases:['sarcasm','silly','irony'],category:'Smileys'},
  {emoji:'😉',name:'winking face',aliases:['wink','flirt','joke'],category:'Smileys'},
  {emoji:'😊',name:'smiling face with smiling eyes',aliases:['blush','happy','cute','smile'],category:'Smileys'},
  {emoji:'😇',name:'smiling face with halo',aliases:['angel','innocent','good'],category:'Smileys'},
  {emoji:'🥰',name:'smiling face with hearts',aliases:['love','adoring','cute','heart'],category:'Smileys'},
  {emoji:'😍',name:'heart eyes',aliases:['love','crush','beautiful','heart'],category:'Smileys'},
  {emoji:'🤩',name:'star struck',aliases:['wow','amazing','stars','hype'],category:'Smileys'},
  {emoji:'😘',name:'face blowing a kiss',aliases:['kiss','love','mwah'],category:'Smileys'},
  {emoji:'😋',name:'face savoring food',aliases:['yum','tasty','tongue'],category:'Smileys'},
  {emoji:'😛',name:'face with tongue',aliases:['tongue','silly','playful'],category:'Smileys'},
  {emoji:'😜',name:'winking face with tongue',aliases:['crazy','silly','tongue','joke'],category:'Smileys'},
  {emoji:'🤪',name:'zany face',aliases:['crazy','wild','silly'],category:'Smileys'},
  {emoji:'😎',name:'smiling face with sunglasses',aliases:['cool','sunglasses','chill'],category:'Smileys'},
  {emoji:'🥳',name:'partying face',aliases:['party','celebrate','birthday','win'],category:'Smileys'},
  {emoji:'😏',name:'smirking face',aliases:['smirk','sus','flirt'],category:'Smileys'},
  {emoji:'😒',name:'unamused face',aliases:['annoyed','meh','unimpressed'],category:'Smileys'},
  {emoji:'😔',name:'pensive face',aliases:['sad','down','sorry'],category:'Smileys'},
  {emoji:'😢',name:'crying face',aliases:['cry','sad','tear'],category:'Smileys'},
  {emoji:'😭',name:'loudly crying face',aliases:['cry','sob','sad','tears'],category:'Smileys'},
  {emoji:'😤',name:'face with steam from nose',aliases:['angry','mad','frustrated'],category:'Smileys'},
  {emoji:'😡',name:'enraged face',aliases:['angry','mad','rage'],category:'Smileys'},
  {emoji:'🤬',name:'face with symbols on mouth',aliases:['swear','angry','rage','cursing'],category:'Smileys'},
  {emoji:'🤯',name:'exploding head',aliases:['mind blown','wow','shock','crazy'],category:'Smileys'},
  {emoji:'😱',name:'face screaming in fear',aliases:['scream','shock','scared','wow'],category:'Smileys'},
  {emoji:'😳',name:'flushed face',aliases:['embarrassed','shock','blush'],category:'Smileys'},
  {emoji:'🥶',name:'cold face',aliases:['cold','freeze','ice'],category:'Smileys'},
  {emoji:'🥵',name:'hot face',aliases:['hot','heat','sweat'],category:'Smileys'},
  {emoji:'🤔',name:'thinking face',aliases:['think','hmm','question'],category:'Smileys'},
  {emoji:'🫡',name:'saluting face',aliases:['salute','respect','yes sir'],category:'Smileys'},
  {emoji:'🤫',name:'shushing face',aliases:['quiet','secret','shh'],category:'Smileys'},
  {emoji:'🤭',name:'face with hand over mouth',aliases:['oops','giggle','shock'],category:'Smileys'},
  {emoji:'🫠',name:'melting face',aliases:['melt','awkward','heat','done'],category:'Smileys'},
  {emoji:'💀',name:'skull',aliases:['dead','dying','lol','death'],category:'Smileys'},
  {emoji:'☠️',name:'skull and crossbones',aliases:['death','danger','dead'],category:'Smileys'},
  {emoji:'👻',name:'ghost',aliases:['spooky','boo','halloween'],category:'Smileys'},
  {emoji:'🤡',name:'clown face',aliases:['clown','fool','joke'],category:'Smileys'},
  {emoji:'💩',name:'pile of poo',aliases:['poop','shit','crap'],category:'Smileys'},
  {emoji:'👀',name:'eyes',aliases:['look','watch','seeing','sus'],category:'People'},
  {emoji:'🧠',name:'brain',aliases:['smart','think','intelligence'],category:'People'},
  {emoji:'🫶',name:'heart hands',aliases:['love','heart','support'],category:'People'},
  {emoji:'👏',name:'clapping hands',aliases:['clap','applause','well done'],category:'People'},
  {emoji:'🙌',name:'raising hands',aliases:['celebrate','praise','yay'],category:'People'},
  {emoji:'👍',name:'thumbs up',aliases:['yes','like','good','approve'],category:'People'},
  {emoji:'👎',name:'thumbs down',aliases:['no','dislike','bad'],category:'People'},
  {emoji:'👌',name:'ok hand',aliases:['okay','perfect','good'],category:'People'},
  {emoji:'✌️',name:'victory hand',aliases:['peace','two','win'],category:'People'},
  {emoji:'🤞',name:'crossed fingers',aliases:['luck','hope','fingers crossed'],category:'People'},
  {emoji:'🤝',name:'handshake',aliases:['deal','agreement','shake'],category:'People'},
  {emoji:'🙏',name:'folded hands',aliases:['pray','please','thanks','thank you'],category:'People'},
  {emoji:'💪',name:'flexed biceps',aliases:['strong','muscle','strength','gym'],category:'People'},
  {emoji:'🫵',name:'index pointing at viewer',aliases:['you','point','your turn'],category:'People'},
  {emoji:'🖕',name:'middle finger',aliases:['middle finger','fuck you','rude'],category:'People'},
  {emoji:'❤️',name:'red heart',aliases:['love','heart','red'],category:'Symbols'},
  {emoji:'🧡',name:'orange heart',aliases:['love','heart','orange'],category:'Symbols'},
  {emoji:'💛',name:'yellow heart',aliases:['love','heart','yellow'],category:'Symbols'},
  {emoji:'💚',name:'green heart',aliases:['love','heart','green'],category:'Symbols'},
  {emoji:'💙',name:'blue heart',aliases:['love','heart','blue'],category:'Symbols'},
  {emoji:'💜',name:'purple heart',aliases:['love','heart','purple'],category:'Symbols'},
  {emoji:'🖤',name:'black heart',aliases:['love','heart','black'],category:'Symbols'},
  {emoji:'🤍',name:'white heart',aliases:['love','heart','white'],category:'Symbols'},
  {emoji:'💔',name:'broken heart',aliases:['heartbreak','sad','breakup'],category:'Symbols'},
  {emoji:'💕',name:'two hearts',aliases:['love','hearts','cute'],category:'Symbols'},
  {emoji:'💯',name:'hundred points',aliases:['100','perfect','facts','real'],category:'Symbols'},
  {emoji:'✅',name:'check mark button',aliases:['check','yes','done','correct'],category:'Symbols'},
  {emoji:'❌',name:'cross mark',aliases:['x','no','wrong','cancel'],category:'Symbols'},
  {emoji:'⚠️',name:'warning',aliases:['alert','danger','caution'],category:'Symbols'},
  {emoji:'🚨',name:'police car light',aliases:['alert','warning','siren','emergency'],category:'Objects'},
  {emoji:'🔥',name:'fire',aliases:['hot','flame','lit','burn','hype'],category:'Nature'},
  {emoji:'✨',name:'sparkles',aliases:['sparkle','shine','magic','new'],category:'Nature'},
  {emoji:'⭐',name:'star',aliases:['star','favorite','good'],category:'Nature'},
  {emoji:'🌟',name:'glowing star',aliases:['star','shine','great'],category:'Nature'},
  {emoji:'⚡',name:'high voltage',aliases:['lightning','fast','speed','electric'],category:'Nature'},
  {emoji:'💥',name:'collision',aliases:['boom','explosion','bang'],category:'Nature'},
  {emoji:'🌈',name:'rainbow',aliases:['rainbow','color','pride'],category:'Nature'},
  {emoji:'☀️',name:'sun',aliases:['sunny','weather','bright'],category:'Nature'},
  {emoji:'🌙',name:'crescent moon',aliases:['moon','night','sleep'],category:'Nature'},
  {emoji:'❄️',name:'snowflake',aliases:['snow','cold','ice'],category:'Nature'},
  {emoji:'🐂',name:'ox',aliases:['bull','bullish','up'],category:'Animals'},
  {emoji:'🐻',name:'bear',aliases:['bearish','down','bear'],category:'Animals'},
  {emoji:'🐸',name:'frog',aliases:['frog','pepe'],category:'Animals'},
  {emoji:'🐶',name:'dog face',aliases:['dog','puppy','doge'],category:'Animals'},
  {emoji:'🐱',name:'cat face',aliases:['cat','kitty'],category:'Animals'},
  {emoji:'🐵',name:'monkey face',aliases:['monkey','ape'],category:'Animals'},
  {emoji:'🦍',name:'gorilla',aliases:['ape','gorilla','strong'],category:'Animals'},
  {emoji:'🦈',name:'shark',aliases:['shark','predator'],category:'Animals'},
  {emoji:'🐳',name:'spouting whale',aliases:['whale','big holder','crypto whale'],category:'Animals'},
  {emoji:'🦅',name:'eagle',aliases:['eagle','bird','freedom'],category:'Animals'},
  {emoji:'🚀',name:'rocket',aliases:['moon','pump','launch','up','rocketship'],category:'Travel'},
  {emoji:'🌕',name:'full moon',aliases:['moon','mooning','pump'],category:'Nature'},
  {emoji:'📈',name:'chart increasing',aliases:['up','profit','green','bullish','pump','gain'],category:'Objects'},
  {emoji:'📉',name:'chart decreasing',aliases:['down','loss','red','bearish','dump'],category:'Objects'},
  {emoji:'💸',name:'money with wings',aliases:['money','cash','spend','loss'],category:'Objects'},
  {emoji:'💰',name:'money bag',aliases:['money','cash','profit','bag'],category:'Objects'},
  {emoji:'🤑',name:'money mouth face',aliases:['money','cash','rich','profit'],category:'Smileys'},
  {emoji:'💵',name:'dollar banknote',aliases:['money','cash','dollar','usd'],category:'Objects'},
  {emoji:'🪙',name:'coin',aliases:['coin','crypto','token','money'],category:'Objects'},
  {emoji:'💎',name:'gem stone',aliases:['diamond','gem','hold','hands'],category:'Objects'},
  {emoji:'🧨',name:'firecracker',aliases:['explode','pump','boom'],category:'Objects'},
  {emoji:'🎯',name:'bullseye',aliases:['target','aim','hit'],category:'Objects'},
  {emoji:'🏆',name:'trophy',aliases:['win','winner','champion'],category:'Objects'},
  {emoji:'🥇',name:'gold medal',aliases:['first','winner','gold'],category:'Objects'},
  {emoji:'🎉',name:'party popper',aliases:['party','celebrate','congrats'],category:'Objects'},
  {emoji:'🎊',name:'confetti ball',aliases:['party','celebrate','confetti'],category:'Objects'},
  {emoji:'🔒',name:'locked',aliases:['lock','secure','private'],category:'Objects'},
  {emoji:'🔓',name:'unlocked',aliases:['unlock','open'],category:'Objects'},
  {emoji:'🔑',name:'key',aliases:['key','access','private key'],category:'Objects'},
  {emoji:'🔍',name:'magnifying glass',aliases:['search','find','look'],category:'Objects'},
  {emoji:'📌',name:'pushpin',aliases:['pin','save','important'],category:'Objects'},
  {emoji:'📣',name:'megaphone',aliases:['announce','announcement','loud'],category:'Objects'},
  {emoji:'🔔',name:'bell',aliases:['notification','alert','ring'],category:'Objects'},
  {emoji:'🧪',name:'test tube',aliases:['test','experiment','lab'],category:'Objects'},
  {emoji:'🛠️',name:'hammer and wrench',aliases:['tools','build','fix','dev'],category:'Objects'},
  {emoji:'💻',name:'laptop',aliases:['computer','code','dev','pc'],category:'Objects'},
  {emoji:'📱',name:'mobile phone',aliases:['phone','mobile','iphone'],category:'Objects'},
  {emoji:'🎮',name:'video game',aliases:['gaming','game','controller'],category:'Objects'},
  {emoji:'🍀',name:'four leaf clover',aliases:['luck','lucky','clover'],category:'Nature'},
  {emoji:'🍻',name:'clinking beer mugs',aliases:['cheers','beer','drink'],category:'Food'},
  {emoji:'🥂',name:'clinking glasses',aliases:['cheers','celebrate','toast'],category:'Food'},
  {emoji:'🍿',name:'popcorn',aliases:['watching','drama','movie'],category:'Food'},
  {emoji:'🫂',name:'people hugging',aliases:['hug','support','friends'],category:'People'},
  {emoji:'🗿',name:'moai',aliases:['stone face','gigachad','meme'],category:'Objects'},
  {emoji:'🧢',name:'billed cap',aliases:['cap','lie','lying','no cap'],category:'Objects'},
  {emoji:'🤌',name:'pinched fingers',aliases:['italian','what','perfect'],category:'People'},
  {emoji:'🤷',name:'person shrugging',aliases:['shrug','idk','dont know'],category:'People'},
  {emoji:'🙈',name:'see no evil monkey',aliases:['monkey','embarrassed','hide'],category:'Smileys'},
  {emoji:'🙉',name:'hear no evil monkey',aliases:['monkey','hear','ignore'],category:'Smileys'},
  {emoji:'🙊',name:'speak no evil monkey',aliases:['monkey','secret','quiet'],category:'Smileys'},
];
